apiVersion: v1                 # Core Kubernetes API group
kind: ConfigMap                # Used to store non-sensitive configuration data
metadata:
  name: app-config             # Name used to reference this ConfigMap in pod
  namespace: form-app


data:
  DB_HOST: mysql-service       # MySQL service DNS name inside cluster
  DB_NAME: formdb              # Database name to be used by backend

