apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: form-app
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS formdb;
    USE formdb;

    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(100),
      email VARCHAR(100),
      phone VARCHAR(15),
      gender VARCHAR(10)
    );

