apiVersion: v1
kind: Secret                   # Used to store sensitive data
metadata:
  name: db-secret              # Secret reference name
  namespace: form-app
type: Opaque                   # Generic key-value secret type

stringData:
  DB_USER: root                # MySQL username
  DB_PASS: password            # MySQL password

