apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: form-app

spec:
  selector:
    app: backend               # Routes traffic to backend pods
  ports:
    - port: 3000               # Service port inside cluster
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: form-app

spec:
  selector:
    app: mysql                 # Routes traffic to MySQL pod
  ports:
    - port: 3306               # MySQL default port
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: form-app

spec:
  type: NodePort               # Exposes frontend outside cluster
  selector:
    app: frontend
  ports:
    - port: 80                 # Service port
      nodePort: 30007          # Port accessible from your laptop browser

